---
vignette: >
  % \VignetteIndexEntry{Mapping PPIs onto 3D protein structures}
  % \VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
    mathjax: null   
---

# Setup

```{r, message = FALSE}
library(BioPlex)
library(graph)
library(bio3d)
library(r3dmol)
```

Map from CORUM complex subunits given as UniProt IDs 
via [SIFTS](https://www.ebi.ac.uk/pdbe/docs/sifts/quick.html) to PDB structures:

```{r}
url <- "ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/flatfiles/csv/uniprot_pdb.csv.gz"
dest <- basename(url)
download.file(url, destfile = dest)
df <- read.csv("uniprot_pdb.csv.gz", skip = 1)
file.remove(dest)
head(df)
```

Turn into a mapping:

```{r}
unip2pdb <- strsplit(df$PDB, ";")
names(unip2pdb) <- df$SP_PRIMARY
head(unip2pdb)
```

Get the PDB structure for the TFIIH core complex 
(PDB ID: [6nmi](https://www.rcsb.org/structure/6NMI))

```{r}
pdb.id <- "6nmi"
pdb.file <- bio3d::get.pdb(pdb.id)
pdb <- bio3d::read.pdb(pdb.file)
pdb
str(pdb)
```

Color for each chain:

```{r}
chains <- unlist(pdb$remark$biomat$chain)
chains
nr.chains <- length(chains)
# chain.colors <- ggpubr::get_palette("ucscgb", nr.chains)
chain.colors <- RColorBrewer::brewer.pal(8, "Set1")
chain.colors <- tolower(chain.colors)
```

Visualize the structure:

```{r}
# Set up the initial viewer
viewer <- r3dmol(
  #viewer_spec = m_viewer_spec(
  #  cartoonQuality = 10,
  #  lowerZoomLimit = 10,
  #  upperZoomLimit = 300
  #),
  id = "",
  elementId = "demo"
) %>%
  # Add model to scene
  m_add_model(data = m_bio3d(pdb), format = "pdb") %>%
  # Zoom to encompass the whole scene
  m_zoom_to() %>%
  # Set style of structures
  m_set_style(style = m_style_cartoon(color = "#00cc96"))
for(i in seq_len(nr.chains))
  viewer <- m_set_style(viewer,
    sel = m_sel(chain = LETTERS[i]),
    style = m_style_cartoon(color = chain.colors[i])
  ) 
viewer %>% m_rotate(angle = 90, axis = "y") %>% m_spin()
```

Pull out the coordinates of each atom:

```{r}
rel.cols <- c("type", "chain", "x", "y", "z")
pos <- pdb$atom[,rel.cols]
head(pos)
```

Compute pairwise distances between atoms:

```{r}
#dmat <- bio3d::dm(pdb)
#dmat[1:5,1:5]
```
