---
title: PFAM domain-domain association analysis
vignette: >
  % \VignetteIndexEntry{PFAM domain-domain association analysis}
  % \VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
    mathjax: null   
---

# Setup

```{r, message = FALSE}
library(BioPlex)
library(AnnotationDbi)
library(AnnotationHub)
library(PFAM.db)
library(graph)
library(ggalluvial)
```

# Data retrieval

Get the latest version of the HCT116 PPI network:

```{r}
bp.hct116 <- BioPlex::getBioPlex(cell.line = "HCT116", version = "1.0")
```

and turn into a graph object:

```{r}
hct.gr <- BioPlex::bioplex2graph(bp.hct116)
hct.gr
```

Annotate PFAM domains to the node metadata:

Connect to 
[AnnotationHub](http://bioconductor.org/packages/AnnotationHub):

```{r ahub, message = FALSE}
ah <- AnnotationHub::AnnotationHub()
```

OrgDb package for human:
```{r orgdb, message = FALSE}
orgdb <- AnnotationHub::query(ah, c("orgDb", "Homo sapiens"))
orgdb <- orgdb[[1]] 
orgdb
AnnotationDbi::keytypes(orgdb)
```

```{r pfam}
hct.gr <- BioPlex::annotatePFAM(hct.gr, orgdb)
```

# Domain-domain association analysis

```{r}
system.time( res.hct <- BioPlexAnalysis::testDomainAssociation(hct.gr) )
head(res.hct)
```

Get human readable description for the PFAM domain IDs:

```{r}
id2de <- as.list(PFAMDE)
id2de <- unlist(id2de)
```

What are the top interacting domain pairs for the HCT116 network:

```{r}
res.hct$DOMAIN1 <- id2de[res.hct$PFAM1]
res.hct$DOMAIN2 <- id2de[res.hct$PFAM2]
head(res.hct)
```

# Visualization

```{r}
top10 <- unique(c(res.hct[1:8,1], res.hct[1:8,2]))
ind <- res.hct[,1] %in% top10 & res.hct[,2] %in% top10
pldf <- res.hct[ind,]
```

```{r, warning = FALSE, fig.width = 6, fig.height = 6}
ggplot(pldf, aes(y = FREQ, axis1 = PFAM1, axis2 = PFAM2)) + 
    geom_alluvium(aes(fill = PFAM1)) + 
    scale_x_discrete(limits = c("PFAM1", "PFAM2"), expand = c(.05, .05)) + 
    geom_stratum(width = 1/12, fill = "lightgrey", color = "darkgrey") + 
    geom_label(stat = "stratum", aes(label = after_stat(stratum))) + 
    ylab("#PPIs") + 
    theme_bw() + theme(legend.position = "none")
```
